name: Check Repositories for New Versions

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:
  
jobs:
  check-releases-and-process:
    runs-on: ubuntu-latest
    env:
      CROMITE_REPO: 'uazo/cromite'
      CHROMEXT_REPO: 'JingMatrix/ChromeXt'
      LSPATCH_REPO: 'JingMatrix/LSPatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Initialize Variables
        run: |
          echo "CROMITE_TAG=$(gh release list -R $CROMITE_REPO --limit=1 --json tagName -q '.[0].tagName')" >> $GITHUB_ENV
          echo "CHROMEXT_TAG=$(gh release list -R $CHROMEXT_REPO --limit=1 --json tagName -q '.[0].tagName')" >> $GITHUB_ENV
          echo "LSPATCH_TAG=$(gh release list -R $LSPATCH_REPO --limit=1 --json tagName -q '.[0].tagName')" >> $GITHUB_ENV

      - name: Check for New Releases
        id: check_releases
        run: |
          # Check if there's a new release since the last run
          # For demonstration, assume we're checking against the last stored tag
          # In practice, you'd need to store the last checked tag, e.g., in a file
          echo "No new releases" # Replace with actual logic

      - name: Download Assets
        if: steps.check_releases.outputs.new_release == 'true'
        run: |
          # Download the assets from the new releases
          # Replace with actual download commands

      - name: Process APK with lspatch.jar
        if: steps.check_releases.outputs.new_release == 'true'
        run: |
          java -jar lspatch.jar x64_ChromePublic.apk -d -v -m ChromeXt-signed.apk --force --injectdex

      - name: Upload Output APK to Release
        if: steps.check_releases.outputs.new_release == 'true'
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output.apk
          asset_name: processed.apk
          asset_content_type: application/octet-stream

      - name: Create Release
        if: steps.check_releases.outputs.new_release == 'true'
        id: create_release
        uses: actions/create-release@v4
        with:
          tag_name: ${{ env.CROMITE_TAG }}
          release_name: Release ${{ env.CROMITE_TAG }}
          draft: false
          prerelease: false
